# -*- mode: ruby -*-
# vi: set ft=ruby : 
# Vagrantfile API/syntax version.  Don't touch unless you know what you're doing! 
VAGRANTFILE_API_VERSION = "2" 

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config| 

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "nrel/CentOS-6.5-x86_64"

  # Caches yum packages to cut down on install time after the first 
  # build.  Note that cached packages will be reused for any other 
  # chef/centos-6.5 boxes.
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  # If true, then any SSH connections made will enable agent forward.
  # Default value: false
  config.ssh.forward_agent = true 

  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", '5734']
    vb.customize ["modifyvm", :id, "--ioapic", 'on']
    vb.customize ["modifyvm", :id, "--cpus", '4']
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.provision "shell" do |s| 
    s.path = "build_box.sh"
    s.privileged = false
  end
end
